name: Release
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build package with Maven
      run: mvn -B package
    - name: Generate documentation
      run: mvn -B javadoc:javadoc
    - name: Publish package
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish documentation
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: gh-pages
        build_dir: target/site/apidocs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
